package com.wimetro.qrcode.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wimetro.qrcode.greendao.entity.Card;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CARD".
*/
public class CardDao extends AbstractDao<Card, Long> {

    public static final String TABLENAME = "CARD";

    /**
     * Properties of entity Card.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CardNo = new Property(1, String.class, "cardNo", false, "CARD_NO");
        public final static Property MF_0005 = new Property(2, String.class, "MF_0005", false, "MF_0005");
        public final static Property ADF1_0015 = new Property(3, String.class, "ADF1_0015", false, "ADF1_0015");
        public final static Property ADF1_0016 = new Property(4, String.class, "ADF1_0016", false, "ADF1_0016");
        public final static Property ADF1_0017_01 = new Property(5, String.class, "ADF1_0017_01", false, "ADF1_0017_01");
        public final static Property Damk_02 = new Property(6, String.class, "damk_02", false, "DAMK_02");
        public final static Property Damk_02_attribute = new Property(7, String.class, "damk_02_attribute", false, "DAMK_02_ATTRIBUTE");
        public final static Property Dpk_01 = new Property(8, String.class, "dpk_01", false, "DPK_01");
        public final static Property Dpk_01_attribute = new Property(9, String.class, "dpk_01_attribute", false, "DPK_01_ATTRIBUTE");
        public final static Property Dpk_02 = new Property(10, String.class, "dpk_02", false, "DPK_02");
        public final static Property Dpk_02_attribute = new Property(11, String.class, "dpk_02_attribute", false, "DPK_02_ATTRIBUTE");
        public final static Property Dpk_03 = new Property(12, String.class, "dpk_03", false, "DPK_03");
        public final static Property Dpk_03_attribute = new Property(13, String.class, "dpk_03_attribute", false, "DPK_03_ATTRIBUTE");
        public final static Property Dpk_04 = new Property(14, String.class, "dpk_04", false, "DPK_04");
        public final static Property Dpk_04_attribute = new Property(15, String.class, "dpk_04_attribute", false, "DPK_04_ATTRIBUTE");
        public final static Property Dpk_05 = new Property(16, String.class, "dpk_05", false, "DPK_05");
        public final static Property Dpk_05_attribute = new Property(17, String.class, "dpk_05_attribute", false, "DPK_05_ATTRIBUTE");
        public final static Property Dlk_01 = new Property(18, String.class, "dlk_01", false, "DLK_01");
        public final static Property Dlk_01_attribute = new Property(19, String.class, "dlk_01_attribute", false, "DLK_01_ATTRIBUTE");
        public final static Property Dlk_02 = new Property(20, String.class, "dlk_02", false, "DLK_02");
        public final static Property Dlk_02_attribute = new Property(21, String.class, "dlk_02_attribute", false, "DLK_02_ATTRIBUTE");
        public final static Property Dlk_03 = new Property(22, String.class, "dlk_03", false, "DLK_03");
        public final static Property Dlk_03_attribute = new Property(23, String.class, "dlk_03_attribute", false, "DLK_03_ATTRIBUTE");
        public final static Property Dlk_04 = new Property(24, String.class, "dlk_04", false, "DLK_04");
        public final static Property Dlk_04_attribute = new Property(25, String.class, "dlk_04_attribute", false, "DLK_04_ATTRIBUTE");
        public final static Property Dlk_05 = new Property(26, String.class, "dlk_05", false, "DLK_05");
        public final static Property Dlk_05_attribute = new Property(27, String.class, "dlk_05_attribute", false, "DLK_05_ATTRIBUTE");
        public final static Property Dtk = new Property(28, String.class, "dtk", false, "DTK");
        public final static Property Dtk_attribute = new Property(29, String.class, "dtk_attribute", false, "DTK_ATTRIBUTE");
        public final static Property Rul = new Property(30, String.class, "rul", false, "RUL");
        public final static Property Create_time = new Property(31, String.class, "create_time", false, "CREATE_TIME");
        public final static Property Fee_total = new Property(32, String.class, "fee_total", false, "FEE_TOTAL");
        public final static Property Onlineval = new Property(33, String.class, "onlineval", false, "ONLINEVAL");
        public final static Property Offlineval = new Property(34, String.class, "offlineval", false, "OFFLINEVAL");
    }


    public CardDao(DaoConfig config) {
        super(config);
    }
    
    public CardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CARD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CARD_NO\" TEXT," + // 1: cardNo
                "\"MF_0005\" TEXT," + // 2: MF_0005
                "\"ADF1_0015\" TEXT," + // 3: ADF1_0015
                "\"ADF1_0016\" TEXT," + // 4: ADF1_0016
                "\"ADF1_0017_01\" TEXT," + // 5: ADF1_0017_01
                "\"DAMK_02\" TEXT," + // 6: damk_02
                "\"DAMK_02_ATTRIBUTE\" TEXT," + // 7: damk_02_attribute
                "\"DPK_01\" TEXT," + // 8: dpk_01
                "\"DPK_01_ATTRIBUTE\" TEXT," + // 9: dpk_01_attribute
                "\"DPK_02\" TEXT," + // 10: dpk_02
                "\"DPK_02_ATTRIBUTE\" TEXT," + // 11: dpk_02_attribute
                "\"DPK_03\" TEXT," + // 12: dpk_03
                "\"DPK_03_ATTRIBUTE\" TEXT," + // 13: dpk_03_attribute
                "\"DPK_04\" TEXT," + // 14: dpk_04
                "\"DPK_04_ATTRIBUTE\" TEXT," + // 15: dpk_04_attribute
                "\"DPK_05\" TEXT," + // 16: dpk_05
                "\"DPK_05_ATTRIBUTE\" TEXT," + // 17: dpk_05_attribute
                "\"DLK_01\" TEXT," + // 18: dlk_01
                "\"DLK_01_ATTRIBUTE\" TEXT," + // 19: dlk_01_attribute
                "\"DLK_02\" TEXT," + // 20: dlk_02
                "\"DLK_02_ATTRIBUTE\" TEXT," + // 21: dlk_02_attribute
                "\"DLK_03\" TEXT," + // 22: dlk_03
                "\"DLK_03_ATTRIBUTE\" TEXT," + // 23: dlk_03_attribute
                "\"DLK_04\" TEXT," + // 24: dlk_04
                "\"DLK_04_ATTRIBUTE\" TEXT," + // 25: dlk_04_attribute
                "\"DLK_05\" TEXT," + // 26: dlk_05
                "\"DLK_05_ATTRIBUTE\" TEXT," + // 27: dlk_05_attribute
                "\"DTK\" TEXT," + // 28: dtk
                "\"DTK_ATTRIBUTE\" TEXT," + // 29: dtk_attribute
                "\"RUL\" TEXT," + // 30: rul
                "\"CREATE_TIME\" TEXT," + // 31: create_time
                "\"FEE_TOTAL\" TEXT," + // 32: fee_total
                "\"ONLINEVAL\" TEXT," + // 33: onlineval
                "\"OFFLINEVAL\" TEXT);"); // 34: offlineval
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CARD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Card entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cardNo = entity.getCardNo();
        if (cardNo != null) {
            stmt.bindString(2, cardNo);
        }
 
        String MF_0005 = entity.getMF_0005();
        if (MF_0005 != null) {
            stmt.bindString(3, MF_0005);
        }
 
        String ADF1_0015 = entity.getADF1_0015();
        if (ADF1_0015 != null) {
            stmt.bindString(4, ADF1_0015);
        }
 
        String ADF1_0016 = entity.getADF1_0016();
        if (ADF1_0016 != null) {
            stmt.bindString(5, ADF1_0016);
        }
 
        String ADF1_0017_01 = entity.getADF1_0017_01();
        if (ADF1_0017_01 != null) {
            stmt.bindString(6, ADF1_0017_01);
        }
 
        String damk_02 = entity.getDamk_02();
        if (damk_02 != null) {
            stmt.bindString(7, damk_02);
        }
 
        String damk_02_attribute = entity.getDamk_02_attribute();
        if (damk_02_attribute != null) {
            stmt.bindString(8, damk_02_attribute);
        }
 
        String dpk_01 = entity.getDpk_01();
        if (dpk_01 != null) {
            stmt.bindString(9, dpk_01);
        }
 
        String dpk_01_attribute = entity.getDpk_01_attribute();
        if (dpk_01_attribute != null) {
            stmt.bindString(10, dpk_01_attribute);
        }
 
        String dpk_02 = entity.getDpk_02();
        if (dpk_02 != null) {
            stmt.bindString(11, dpk_02);
        }
 
        String dpk_02_attribute = entity.getDpk_02_attribute();
        if (dpk_02_attribute != null) {
            stmt.bindString(12, dpk_02_attribute);
        }
 
        String dpk_03 = entity.getDpk_03();
        if (dpk_03 != null) {
            stmt.bindString(13, dpk_03);
        }
 
        String dpk_03_attribute = entity.getDpk_03_attribute();
        if (dpk_03_attribute != null) {
            stmt.bindString(14, dpk_03_attribute);
        }
 
        String dpk_04 = entity.getDpk_04();
        if (dpk_04 != null) {
            stmt.bindString(15, dpk_04);
        }
 
        String dpk_04_attribute = entity.getDpk_04_attribute();
        if (dpk_04_attribute != null) {
            stmt.bindString(16, dpk_04_attribute);
        }
 
        String dpk_05 = entity.getDpk_05();
        if (dpk_05 != null) {
            stmt.bindString(17, dpk_05);
        }
 
        String dpk_05_attribute = entity.getDpk_05_attribute();
        if (dpk_05_attribute != null) {
            stmt.bindString(18, dpk_05_attribute);
        }
 
        String dlk_01 = entity.getDlk_01();
        if (dlk_01 != null) {
            stmt.bindString(19, dlk_01);
        }
 
        String dlk_01_attribute = entity.getDlk_01_attribute();
        if (dlk_01_attribute != null) {
            stmt.bindString(20, dlk_01_attribute);
        }
 
        String dlk_02 = entity.getDlk_02();
        if (dlk_02 != null) {
            stmt.bindString(21, dlk_02);
        }
 
        String dlk_02_attribute = entity.getDlk_02_attribute();
        if (dlk_02_attribute != null) {
            stmt.bindString(22, dlk_02_attribute);
        }
 
        String dlk_03 = entity.getDlk_03();
        if (dlk_03 != null) {
            stmt.bindString(23, dlk_03);
        }
 
        String dlk_03_attribute = entity.getDlk_03_attribute();
        if (dlk_03_attribute != null) {
            stmt.bindString(24, dlk_03_attribute);
        }
 
        String dlk_04 = entity.getDlk_04();
        if (dlk_04 != null) {
            stmt.bindString(25, dlk_04);
        }
 
        String dlk_04_attribute = entity.getDlk_04_attribute();
        if (dlk_04_attribute != null) {
            stmt.bindString(26, dlk_04_attribute);
        }
 
        String dlk_05 = entity.getDlk_05();
        if (dlk_05 != null) {
            stmt.bindString(27, dlk_05);
        }
 
        String dlk_05_attribute = entity.getDlk_05_attribute();
        if (dlk_05_attribute != null) {
            stmt.bindString(28, dlk_05_attribute);
        }
 
        String dtk = entity.getDtk();
        if (dtk != null) {
            stmt.bindString(29, dtk);
        }
 
        String dtk_attribute = entity.getDtk_attribute();
        if (dtk_attribute != null) {
            stmt.bindString(30, dtk_attribute);
        }
 
        String rul = entity.getRul();
        if (rul != null) {
            stmt.bindString(31, rul);
        }
 
        String create_time = entity.getCreate_time();
        if (create_time != null) {
            stmt.bindString(32, create_time);
        }
 
        String fee_total = entity.getFee_total();
        if (fee_total != null) {
            stmt.bindString(33, fee_total);
        }
 
        String onlineval = entity.getOnlineval();
        if (onlineval != null) {
            stmt.bindString(34, onlineval);
        }
 
        String offlineval = entity.getOfflineval();
        if (offlineval != null) {
            stmt.bindString(35, offlineval);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Card entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cardNo = entity.getCardNo();
        if (cardNo != null) {
            stmt.bindString(2, cardNo);
        }
 
        String MF_0005 = entity.getMF_0005();
        if (MF_0005 != null) {
            stmt.bindString(3, MF_0005);
        }
 
        String ADF1_0015 = entity.getADF1_0015();
        if (ADF1_0015 != null) {
            stmt.bindString(4, ADF1_0015);
        }
 
        String ADF1_0016 = entity.getADF1_0016();
        if (ADF1_0016 != null) {
            stmt.bindString(5, ADF1_0016);
        }
 
        String ADF1_0017_01 = entity.getADF1_0017_01();
        if (ADF1_0017_01 != null) {
            stmt.bindString(6, ADF1_0017_01);
        }
 
        String damk_02 = entity.getDamk_02();
        if (damk_02 != null) {
            stmt.bindString(7, damk_02);
        }
 
        String damk_02_attribute = entity.getDamk_02_attribute();
        if (damk_02_attribute != null) {
            stmt.bindString(8, damk_02_attribute);
        }
 
        String dpk_01 = entity.getDpk_01();
        if (dpk_01 != null) {
            stmt.bindString(9, dpk_01);
        }
 
        String dpk_01_attribute = entity.getDpk_01_attribute();
        if (dpk_01_attribute != null) {
            stmt.bindString(10, dpk_01_attribute);
        }
 
        String dpk_02 = entity.getDpk_02();
        if (dpk_02 != null) {
            stmt.bindString(11, dpk_02);
        }
 
        String dpk_02_attribute = entity.getDpk_02_attribute();
        if (dpk_02_attribute != null) {
            stmt.bindString(12, dpk_02_attribute);
        }
 
        String dpk_03 = entity.getDpk_03();
        if (dpk_03 != null) {
            stmt.bindString(13, dpk_03);
        }
 
        String dpk_03_attribute = entity.getDpk_03_attribute();
        if (dpk_03_attribute != null) {
            stmt.bindString(14, dpk_03_attribute);
        }
 
        String dpk_04 = entity.getDpk_04();
        if (dpk_04 != null) {
            stmt.bindString(15, dpk_04);
        }
 
        String dpk_04_attribute = entity.getDpk_04_attribute();
        if (dpk_04_attribute != null) {
            stmt.bindString(16, dpk_04_attribute);
        }
 
        String dpk_05 = entity.getDpk_05();
        if (dpk_05 != null) {
            stmt.bindString(17, dpk_05);
        }
 
        String dpk_05_attribute = entity.getDpk_05_attribute();
        if (dpk_05_attribute != null) {
            stmt.bindString(18, dpk_05_attribute);
        }
 
        String dlk_01 = entity.getDlk_01();
        if (dlk_01 != null) {
            stmt.bindString(19, dlk_01);
        }
 
        String dlk_01_attribute = entity.getDlk_01_attribute();
        if (dlk_01_attribute != null) {
            stmt.bindString(20, dlk_01_attribute);
        }
 
        String dlk_02 = entity.getDlk_02();
        if (dlk_02 != null) {
            stmt.bindString(21, dlk_02);
        }
 
        String dlk_02_attribute = entity.getDlk_02_attribute();
        if (dlk_02_attribute != null) {
            stmt.bindString(22, dlk_02_attribute);
        }
 
        String dlk_03 = entity.getDlk_03();
        if (dlk_03 != null) {
            stmt.bindString(23, dlk_03);
        }
 
        String dlk_03_attribute = entity.getDlk_03_attribute();
        if (dlk_03_attribute != null) {
            stmt.bindString(24, dlk_03_attribute);
        }
 
        String dlk_04 = entity.getDlk_04();
        if (dlk_04 != null) {
            stmt.bindString(25, dlk_04);
        }
 
        String dlk_04_attribute = entity.getDlk_04_attribute();
        if (dlk_04_attribute != null) {
            stmt.bindString(26, dlk_04_attribute);
        }
 
        String dlk_05 = entity.getDlk_05();
        if (dlk_05 != null) {
            stmt.bindString(27, dlk_05);
        }
 
        String dlk_05_attribute = entity.getDlk_05_attribute();
        if (dlk_05_attribute != null) {
            stmt.bindString(28, dlk_05_attribute);
        }
 
        String dtk = entity.getDtk();
        if (dtk != null) {
            stmt.bindString(29, dtk);
        }
 
        String dtk_attribute = entity.getDtk_attribute();
        if (dtk_attribute != null) {
            stmt.bindString(30, dtk_attribute);
        }
 
        String rul = entity.getRul();
        if (rul != null) {
            stmt.bindString(31, rul);
        }
 
        String create_time = entity.getCreate_time();
        if (create_time != null) {
            stmt.bindString(32, create_time);
        }
 
        String fee_total = entity.getFee_total();
        if (fee_total != null) {
            stmt.bindString(33, fee_total);
        }
 
        String onlineval = entity.getOnlineval();
        if (onlineval != null) {
            stmt.bindString(34, onlineval);
        }
 
        String offlineval = entity.getOfflineval();
        if (offlineval != null) {
            stmt.bindString(35, offlineval);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Card readEntity(Cursor cursor, int offset) {
        Card entity = new Card( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cardNo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // MF_0005
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ADF1_0015
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ADF1_0016
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // ADF1_0017_01
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // damk_02
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // damk_02_attribute
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // dpk_01
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // dpk_01_attribute
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // dpk_02
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // dpk_02_attribute
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // dpk_03
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // dpk_03_attribute
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // dpk_04
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // dpk_04_attribute
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // dpk_05
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // dpk_05_attribute
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // dlk_01
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // dlk_01_attribute
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // dlk_02
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // dlk_02_attribute
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // dlk_03
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // dlk_03_attribute
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // dlk_04
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // dlk_04_attribute
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // dlk_05
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // dlk_05_attribute
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // dtk
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // dtk_attribute
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // rul
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // create_time
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // fee_total
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // onlineval
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34) // offlineval
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Card entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCardNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMF_0005(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setADF1_0015(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setADF1_0016(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setADF1_0017_01(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDamk_02(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDamk_02_attribute(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDpk_01(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDpk_01_attribute(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setDpk_02(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setDpk_02_attribute(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setDpk_03(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setDpk_03_attribute(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setDpk_04(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setDpk_04_attribute(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setDpk_05(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setDpk_05_attribute(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setDlk_01(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setDlk_01_attribute(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setDlk_02(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setDlk_02_attribute(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setDlk_03(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setDlk_03_attribute(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setDlk_04(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setDlk_04_attribute(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setDlk_05(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setDlk_05_attribute(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setDtk(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setDtk_attribute(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setRul(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setCreate_time(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setFee_total(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setOnlineval(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setOfflineval(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Card entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Card entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Card entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
