package com.wimetro.qrcode.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wimetro.qrcode.greendao.entity.Card;
import com.wimetro.qrcode.greendao.entity.Moblie;
import com.wimetro.qrcode.greendao.entity.Station;
import com.wimetro.qrcode.greendao.entity.StationCache;
import com.wimetro.qrcode.greendao.entity.User;

import com.wimetro.qrcode.greendao.CardDao;
import com.wimetro.qrcode.greendao.MoblieDao;
import com.wimetro.qrcode.greendao.StationDao;
import com.wimetro.qrcode.greendao.StationCacheDao;
import com.wimetro.qrcode.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardDaoConfig;
    private final DaoConfig moblieDaoConfig;
    private final DaoConfig stationDaoConfig;
    private final DaoConfig stationCacheDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CardDao cardDao;
    private final MoblieDao moblieDao;
    private final StationDao stationDao;
    private final StationCacheDao stationCacheDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardDaoConfig = daoConfigMap.get(CardDao.class).clone();
        cardDaoConfig.initIdentityScope(type);

        moblieDaoConfig = daoConfigMap.get(MoblieDao.class).clone();
        moblieDaoConfig.initIdentityScope(type);

        stationDaoConfig = daoConfigMap.get(StationDao.class).clone();
        stationDaoConfig.initIdentityScope(type);

        stationCacheDaoConfig = daoConfigMap.get(StationCacheDao.class).clone();
        stationCacheDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        cardDao = new CardDao(cardDaoConfig, this);
        moblieDao = new MoblieDao(moblieDaoConfig, this);
        stationDao = new StationDao(stationDaoConfig, this);
        stationCacheDao = new StationCacheDao(stationCacheDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Card.class, cardDao);
        registerDao(Moblie.class, moblieDao);
        registerDao(Station.class, stationDao);
        registerDao(StationCache.class, stationCacheDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        cardDaoConfig.clearIdentityScope();
        moblieDaoConfig.clearIdentityScope();
        stationDaoConfig.clearIdentityScope();
        stationCacheDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CardDao getCardDao() {
        return cardDao;
    }

    public MoblieDao getMoblieDao() {
        return moblieDao;
    }

    public StationDao getStationDao() {
        return stationDao;
    }

    public StationCacheDao getStationCacheDao() {
        return stationCacheDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
