package com.wimetro.qrcode.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wimetro.qrcode.greendao.entity.Moblie;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOBLIE".
*/
public class MoblieDao extends AbstractDao<Moblie, Long> {

    public static final String TABLENAME = "MOBLIE";

    /**
     * Properties of entity Moblie.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Mobile_type = new Property(1, String.class, "mobile_type", false, "MOBILE_TYPE");
        public final static Property Mobile_code = new Property(2, String.class, "mobile_code", false, "MOBILE_CODE");
        public final static Property Mobile_name = new Property(3, String.class, "mobile_name", false, "MOBILE_NAME");
    }


    public MoblieDao(DaoConfig config) {
        super(config);
    }
    
    public MoblieDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOBLIE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MOBILE_TYPE\" TEXT," + // 1: mobile_type
                "\"MOBILE_CODE\" TEXT," + // 2: mobile_code
                "\"MOBILE_NAME\" TEXT);"); // 3: mobile_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOBLIE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Moblie entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mobile_type = entity.getMobile_type();
        if (mobile_type != null) {
            stmt.bindString(2, mobile_type);
        }
 
        String mobile_code = entity.getMobile_code();
        if (mobile_code != null) {
            stmt.bindString(3, mobile_code);
        }
 
        String mobile_name = entity.getMobile_name();
        if (mobile_name != null) {
            stmt.bindString(4, mobile_name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Moblie entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mobile_type = entity.getMobile_type();
        if (mobile_type != null) {
            stmt.bindString(2, mobile_type);
        }
 
        String mobile_code = entity.getMobile_code();
        if (mobile_code != null) {
            stmt.bindString(3, mobile_code);
        }
 
        String mobile_name = entity.getMobile_name();
        if (mobile_name != null) {
            stmt.bindString(4, mobile_name);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Moblie readEntity(Cursor cursor, int offset) {
        Moblie entity = new Moblie( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mobile_type
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mobile_code
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // mobile_name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Moblie entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMobile_type(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMobile_code(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMobile_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Moblie entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Moblie entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Moblie entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
