package com.wimetro.qrcode.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wimetro.qrcode.greendao.entity.Station;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STATION".
*/
public class StationDao extends AbstractDao<Station, Long> {

    public static final String TABLENAME = "STATION";

    /**
     * Properties of entity Station.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Hce_id = new Property(1, String.class, "hce_id", false, "HCE_ID");
        public final static Property Info_type = new Property(2, String.class, "info_type", false, "INFO_TYPE");
        public final static Property Deal_device_code = new Property(3, String.class, "deal_device_code", false, "DEAL_DEVICE_CODE");
        public final static Property Deal_seq_group_no = new Property(4, String.class, "deal_seq_group_no", false, "DEAL_SEQ_GROUP_NO");
        public final static Property Deal_seq_no = new Property(5, String.class, "deal_seq_no", false, "DEAL_SEQ_NO");
        public final static Property Deal_station = new Property(6, String.class, "deal_station", false, "DEAL_STATION");
        public final static Property Deal_type = new Property(7, String.class, "deal_type", false, "DEAL_TYPE");
        public final static Property Main_type = new Property(8, String.class, "main_type", false, "MAIN_TYPE");
        public final static Property Sub_type = new Property(9, String.class, "sub_type", false, "SUB_TYPE");
        public final static Property Area_code = new Property(10, String.class, "area_code", false, "AREA_CODE");
        public final static Property Sam_code = new Property(11, String.class, "sam_code", false, "SAM_CODE");
        public final static Property Logical_code = new Property(12, String.class, "logical_code", false, "LOGICAL_CODE");
        public final static Property Read_count = new Property(13, String.class, "read_count", false, "READ_COUNT");
        public final static Property Deal_amount = new Property(14, String.class, "deal_amount", false, "DEAL_AMOUNT");
        public final static Property Balance = new Property(15, String.class, "balance", false, "BALANCE");
        public final static Property Deal_time = new Property(16, String.class, "deal_time", false, "DEAL_TIME");
        public final static Property Last_deal_dev_code = new Property(17, String.class, "last_deal_dev_code", false, "LAST_DEAL_DEV_CODE");
        public final static Property Last_deal_sq_no = new Property(18, String.class, "last_deal_sq_no", false, "LAST_DEAL_SQ_NO");
        public final static Property Last_deal_amount = new Property(19, String.class, "last_deal_amount", false, "LAST_DEAL_AMOUNT");
        public final static Property Last_deal_time = new Property(20, String.class, "last_deal_time", false, "LAST_DEAL_TIME");
        public final static Property Tac = new Property(21, String.class, "tac", false, "TAC");
        public final static Property Degrade_mode = new Property(22, String.class, "degrade_mode", false, "DEGRADE_MODE");
        public final static Property In_gate_station = new Property(23, String.class, "in_gate_station", false, "IN_GATE_STATION");
        public final static Property In_gate_dev = new Property(24, String.class, "in_gate_dev", false, "IN_GATE_DEV");
        public final static Property In_gate_time = new Property(25, String.class, "in_gate_time", false, "IN_GATE_TIME");
        public final static Property Pay_type = new Property(26, String.class, "pay_type", false, "PAY_TYPE");
        public final static Property Pay_card_no = new Property(27, String.class, "pay_card_no", false, "PAY_CARD_NO");
        public final static Property Destination_station = new Property(28, String.class, "destination_station", false, "DESTINATION_STATION");
        public final static Property Deal_cause = new Property(29, String.class, "deal_cause", false, "DEAL_CAUSE");
        public final static Property Deal_total_amount = new Property(30, String.class, "deal_total_amount", false, "DEAL_TOTAL_AMOUNT");
        public final static Property Deposit = new Property(31, String.class, "deposit", false, "DEPOSIT");
        public final static Property Deal_fee = new Property(32, String.class, "deal_fee", false, "DEAL_FEE");
        public final static Property Expiry_date = new Property(33, String.class, "expiry_date", false, "EXPIRY_DATE");
        public final static Property Last_expiry_date = new Property(34, String.class, "last_expiry_date", false, "LAST_EXPIRY_DATE");
        public final static Property Oper_id = new Property(35, String.class, "oper_id", false, "OPER_ID");
        public final static Property Work_sq_no = new Property(36, String.class, "work_sq_no", false, "WORK_SQ_NO");
        public final static Property Info_id = new Property(37, String.class, "info_id", false, "INFO_ID");
        public final static Property Is_report = new Property(38, String.class, "is_report", false, "IS_REPORT");
        public final static Property PhoneType = new Property(39, String.class, "phoneType", false, "PHONE_TYPE");
        public final static Property Para_1 = new Property(40, String.class, "para_1", false, "PARA_1");
        public final static Property Para_2 = new Property(41, String.class, "para_2", false, "PARA_2");
        public final static Property Para_3 = new Property(42, String.class, "para_3", false, "PARA_3");
    }


    public StationDao(DaoConfig config) {
        super(config);
    }
    
    public StationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"HCE_ID\" TEXT," + // 1: hce_id
                "\"INFO_TYPE\" TEXT," + // 2: info_type
                "\"DEAL_DEVICE_CODE\" TEXT," + // 3: deal_device_code
                "\"DEAL_SEQ_GROUP_NO\" TEXT," + // 4: deal_seq_group_no
                "\"DEAL_SEQ_NO\" TEXT," + // 5: deal_seq_no
                "\"DEAL_STATION\" TEXT," + // 6: deal_station
                "\"DEAL_TYPE\" TEXT," + // 7: deal_type
                "\"MAIN_TYPE\" TEXT," + // 8: main_type
                "\"SUB_TYPE\" TEXT," + // 9: sub_type
                "\"AREA_CODE\" TEXT," + // 10: area_code
                "\"SAM_CODE\" TEXT," + // 11: sam_code
                "\"LOGICAL_CODE\" TEXT," + // 12: logical_code
                "\"READ_COUNT\" TEXT," + // 13: read_count
                "\"DEAL_AMOUNT\" TEXT," + // 14: deal_amount
                "\"BALANCE\" TEXT," + // 15: balance
                "\"DEAL_TIME\" TEXT," + // 16: deal_time
                "\"LAST_DEAL_DEV_CODE\" TEXT," + // 17: last_deal_dev_code
                "\"LAST_DEAL_SQ_NO\" TEXT," + // 18: last_deal_sq_no
                "\"LAST_DEAL_AMOUNT\" TEXT," + // 19: last_deal_amount
                "\"LAST_DEAL_TIME\" TEXT," + // 20: last_deal_time
                "\"TAC\" TEXT," + // 21: tac
                "\"DEGRADE_MODE\" TEXT," + // 22: degrade_mode
                "\"IN_GATE_STATION\" TEXT," + // 23: in_gate_station
                "\"IN_GATE_DEV\" TEXT," + // 24: in_gate_dev
                "\"IN_GATE_TIME\" TEXT," + // 25: in_gate_time
                "\"PAY_TYPE\" TEXT," + // 26: pay_type
                "\"PAY_CARD_NO\" TEXT," + // 27: pay_card_no
                "\"DESTINATION_STATION\" TEXT," + // 28: destination_station
                "\"DEAL_CAUSE\" TEXT," + // 29: deal_cause
                "\"DEAL_TOTAL_AMOUNT\" TEXT," + // 30: deal_total_amount
                "\"DEPOSIT\" TEXT," + // 31: deposit
                "\"DEAL_FEE\" TEXT," + // 32: deal_fee
                "\"EXPIRY_DATE\" TEXT," + // 33: expiry_date
                "\"LAST_EXPIRY_DATE\" TEXT," + // 34: last_expiry_date
                "\"OPER_ID\" TEXT," + // 35: oper_id
                "\"WORK_SQ_NO\" TEXT," + // 36: work_sq_no
                "\"INFO_ID\" TEXT," + // 37: info_id
                "\"IS_REPORT\" TEXT," + // 38: is_report
                "\"PHONE_TYPE\" TEXT," + // 39: phoneType
                "\"PARA_1\" TEXT," + // 40: para_1
                "\"PARA_2\" TEXT," + // 41: para_2
                "\"PARA_3\" TEXT);"); // 42: para_3
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Station entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String hce_id = entity.getHce_id();
        if (hce_id != null) {
            stmt.bindString(2, hce_id);
        }
 
        String info_type = entity.getInfo_type();
        if (info_type != null) {
            stmt.bindString(3, info_type);
        }
 
        String deal_device_code = entity.getDeal_device_code();
        if (deal_device_code != null) {
            stmt.bindString(4, deal_device_code);
        }
 
        String deal_seq_group_no = entity.getDeal_seq_group_no();
        if (deal_seq_group_no != null) {
            stmt.bindString(5, deal_seq_group_no);
        }
 
        String deal_seq_no = entity.getDeal_seq_no();
        if (deal_seq_no != null) {
            stmt.bindString(6, deal_seq_no);
        }
 
        String deal_station = entity.getDeal_station();
        if (deal_station != null) {
            stmt.bindString(7, deal_station);
        }
 
        String deal_type = entity.getDeal_type();
        if (deal_type != null) {
            stmt.bindString(8, deal_type);
        }
 
        String main_type = entity.getMain_type();
        if (main_type != null) {
            stmt.bindString(9, main_type);
        }
 
        String sub_type = entity.getSub_type();
        if (sub_type != null) {
            stmt.bindString(10, sub_type);
        }
 
        String area_code = entity.getArea_code();
        if (area_code != null) {
            stmt.bindString(11, area_code);
        }
 
        String sam_code = entity.getSam_code();
        if (sam_code != null) {
            stmt.bindString(12, sam_code);
        }
 
        String logical_code = entity.getLogical_code();
        if (logical_code != null) {
            stmt.bindString(13, logical_code);
        }
 
        String read_count = entity.getRead_count();
        if (read_count != null) {
            stmt.bindString(14, read_count);
        }
 
        String deal_amount = entity.getDeal_amount();
        if (deal_amount != null) {
            stmt.bindString(15, deal_amount);
        }
 
        String balance = entity.getBalance();
        if (balance != null) {
            stmt.bindString(16, balance);
        }
 
        String deal_time = entity.getDeal_time();
        if (deal_time != null) {
            stmt.bindString(17, deal_time);
        }
 
        String last_deal_dev_code = entity.getLast_deal_dev_code();
        if (last_deal_dev_code != null) {
            stmt.bindString(18, last_deal_dev_code);
        }
 
        String last_deal_sq_no = entity.getLast_deal_sq_no();
        if (last_deal_sq_no != null) {
            stmt.bindString(19, last_deal_sq_no);
        }
 
        String last_deal_amount = entity.getLast_deal_amount();
        if (last_deal_amount != null) {
            stmt.bindString(20, last_deal_amount);
        }
 
        String last_deal_time = entity.getLast_deal_time();
        if (last_deal_time != null) {
            stmt.bindString(21, last_deal_time);
        }
 
        String tac = entity.getTac();
        if (tac != null) {
            stmt.bindString(22, tac);
        }
 
        String degrade_mode = entity.getDegrade_mode();
        if (degrade_mode != null) {
            stmt.bindString(23, degrade_mode);
        }
 
        String in_gate_station = entity.getIn_gate_station();
        if (in_gate_station != null) {
            stmt.bindString(24, in_gate_station);
        }
 
        String in_gate_dev = entity.getIn_gate_dev();
        if (in_gate_dev != null) {
            stmt.bindString(25, in_gate_dev);
        }
 
        String in_gate_time = entity.getIn_gate_time();
        if (in_gate_time != null) {
            stmt.bindString(26, in_gate_time);
        }
 
        String pay_type = entity.getPay_type();
        if (pay_type != null) {
            stmt.bindString(27, pay_type);
        }
 
        String pay_card_no = entity.getPay_card_no();
        if (pay_card_no != null) {
            stmt.bindString(28, pay_card_no);
        }
 
        String destination_station = entity.getDestination_station();
        if (destination_station != null) {
            stmt.bindString(29, destination_station);
        }
 
        String deal_cause = entity.getDeal_cause();
        if (deal_cause != null) {
            stmt.bindString(30, deal_cause);
        }
 
        String deal_total_amount = entity.getDeal_total_amount();
        if (deal_total_amount != null) {
            stmt.bindString(31, deal_total_amount);
        }
 
        String deposit = entity.getDeposit();
        if (deposit != null) {
            stmt.bindString(32, deposit);
        }
 
        String deal_fee = entity.getDeal_fee();
        if (deal_fee != null) {
            stmt.bindString(33, deal_fee);
        }
 
        String expiry_date = entity.getExpiry_date();
        if (expiry_date != null) {
            stmt.bindString(34, expiry_date);
        }
 
        String last_expiry_date = entity.getLast_expiry_date();
        if (last_expiry_date != null) {
            stmt.bindString(35, last_expiry_date);
        }
 
        String oper_id = entity.getOper_id();
        if (oper_id != null) {
            stmt.bindString(36, oper_id);
        }
 
        String work_sq_no = entity.getWork_sq_no();
        if (work_sq_no != null) {
            stmt.bindString(37, work_sq_no);
        }
 
        String info_id = entity.getInfo_id();
        if (info_id != null) {
            stmt.bindString(38, info_id);
        }
 
        String is_report = entity.getIs_report();
        if (is_report != null) {
            stmt.bindString(39, is_report);
        }
 
        String phoneType = entity.getPhoneType();
        if (phoneType != null) {
            stmt.bindString(40, phoneType);
        }
 
        String para_1 = entity.getPara_1();
        if (para_1 != null) {
            stmt.bindString(41, para_1);
        }
 
        String para_2 = entity.getPara_2();
        if (para_2 != null) {
            stmt.bindString(42, para_2);
        }
 
        String para_3 = entity.getPara_3();
        if (para_3 != null) {
            stmt.bindString(43, para_3);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Station entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String hce_id = entity.getHce_id();
        if (hce_id != null) {
            stmt.bindString(2, hce_id);
        }
 
        String info_type = entity.getInfo_type();
        if (info_type != null) {
            stmt.bindString(3, info_type);
        }
 
        String deal_device_code = entity.getDeal_device_code();
        if (deal_device_code != null) {
            stmt.bindString(4, deal_device_code);
        }
 
        String deal_seq_group_no = entity.getDeal_seq_group_no();
        if (deal_seq_group_no != null) {
            stmt.bindString(5, deal_seq_group_no);
        }
 
        String deal_seq_no = entity.getDeal_seq_no();
        if (deal_seq_no != null) {
            stmt.bindString(6, deal_seq_no);
        }
 
        String deal_station = entity.getDeal_station();
        if (deal_station != null) {
            stmt.bindString(7, deal_station);
        }
 
        String deal_type = entity.getDeal_type();
        if (deal_type != null) {
            stmt.bindString(8, deal_type);
        }
 
        String main_type = entity.getMain_type();
        if (main_type != null) {
            stmt.bindString(9, main_type);
        }
 
        String sub_type = entity.getSub_type();
        if (sub_type != null) {
            stmt.bindString(10, sub_type);
        }
 
        String area_code = entity.getArea_code();
        if (area_code != null) {
            stmt.bindString(11, area_code);
        }
 
        String sam_code = entity.getSam_code();
        if (sam_code != null) {
            stmt.bindString(12, sam_code);
        }
 
        String logical_code = entity.getLogical_code();
        if (logical_code != null) {
            stmt.bindString(13, logical_code);
        }
 
        String read_count = entity.getRead_count();
        if (read_count != null) {
            stmt.bindString(14, read_count);
        }
 
        String deal_amount = entity.getDeal_amount();
        if (deal_amount != null) {
            stmt.bindString(15, deal_amount);
        }
 
        String balance = entity.getBalance();
        if (balance != null) {
            stmt.bindString(16, balance);
        }
 
        String deal_time = entity.getDeal_time();
        if (deal_time != null) {
            stmt.bindString(17, deal_time);
        }
 
        String last_deal_dev_code = entity.getLast_deal_dev_code();
        if (last_deal_dev_code != null) {
            stmt.bindString(18, last_deal_dev_code);
        }
 
        String last_deal_sq_no = entity.getLast_deal_sq_no();
        if (last_deal_sq_no != null) {
            stmt.bindString(19, last_deal_sq_no);
        }
 
        String last_deal_amount = entity.getLast_deal_amount();
        if (last_deal_amount != null) {
            stmt.bindString(20, last_deal_amount);
        }
 
        String last_deal_time = entity.getLast_deal_time();
        if (last_deal_time != null) {
            stmt.bindString(21, last_deal_time);
        }
 
        String tac = entity.getTac();
        if (tac != null) {
            stmt.bindString(22, tac);
        }
 
        String degrade_mode = entity.getDegrade_mode();
        if (degrade_mode != null) {
            stmt.bindString(23, degrade_mode);
        }
 
        String in_gate_station = entity.getIn_gate_station();
        if (in_gate_station != null) {
            stmt.bindString(24, in_gate_station);
        }
 
        String in_gate_dev = entity.getIn_gate_dev();
        if (in_gate_dev != null) {
            stmt.bindString(25, in_gate_dev);
        }
 
        String in_gate_time = entity.getIn_gate_time();
        if (in_gate_time != null) {
            stmt.bindString(26, in_gate_time);
        }
 
        String pay_type = entity.getPay_type();
        if (pay_type != null) {
            stmt.bindString(27, pay_type);
        }
 
        String pay_card_no = entity.getPay_card_no();
        if (pay_card_no != null) {
            stmt.bindString(28, pay_card_no);
        }
 
        String destination_station = entity.getDestination_station();
        if (destination_station != null) {
            stmt.bindString(29, destination_station);
        }
 
        String deal_cause = entity.getDeal_cause();
        if (deal_cause != null) {
            stmt.bindString(30, deal_cause);
        }
 
        String deal_total_amount = entity.getDeal_total_amount();
        if (deal_total_amount != null) {
            stmt.bindString(31, deal_total_amount);
        }
 
        String deposit = entity.getDeposit();
        if (deposit != null) {
            stmt.bindString(32, deposit);
        }
 
        String deal_fee = entity.getDeal_fee();
        if (deal_fee != null) {
            stmt.bindString(33, deal_fee);
        }
 
        String expiry_date = entity.getExpiry_date();
        if (expiry_date != null) {
            stmt.bindString(34, expiry_date);
        }
 
        String last_expiry_date = entity.getLast_expiry_date();
        if (last_expiry_date != null) {
            stmt.bindString(35, last_expiry_date);
        }
 
        String oper_id = entity.getOper_id();
        if (oper_id != null) {
            stmt.bindString(36, oper_id);
        }
 
        String work_sq_no = entity.getWork_sq_no();
        if (work_sq_no != null) {
            stmt.bindString(37, work_sq_no);
        }
 
        String info_id = entity.getInfo_id();
        if (info_id != null) {
            stmt.bindString(38, info_id);
        }
 
        String is_report = entity.getIs_report();
        if (is_report != null) {
            stmt.bindString(39, is_report);
        }
 
        String phoneType = entity.getPhoneType();
        if (phoneType != null) {
            stmt.bindString(40, phoneType);
        }
 
        String para_1 = entity.getPara_1();
        if (para_1 != null) {
            stmt.bindString(41, para_1);
        }
 
        String para_2 = entity.getPara_2();
        if (para_2 != null) {
            stmt.bindString(42, para_2);
        }
 
        String para_3 = entity.getPara_3();
        if (para_3 != null) {
            stmt.bindString(43, para_3);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Station readEntity(Cursor cursor, int offset) {
        Station entity = new Station( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // hce_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // info_type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // deal_device_code
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // deal_seq_group_no
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // deal_seq_no
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // deal_station
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // deal_type
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // main_type
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // sub_type
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // area_code
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // sam_code
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // logical_code
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // read_count
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // deal_amount
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // balance
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // deal_time
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // last_deal_dev_code
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // last_deal_sq_no
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // last_deal_amount
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // last_deal_time
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // tac
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // degrade_mode
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // in_gate_station
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // in_gate_dev
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // in_gate_time
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // pay_type
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // pay_card_no
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // destination_station
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // deal_cause
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // deal_total_amount
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // deposit
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // deal_fee
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // expiry_date
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // last_expiry_date
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // oper_id
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // work_sq_no
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // info_id
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // is_report
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // phoneType
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // para_1
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // para_2
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42) // para_3
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Station entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHce_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setInfo_type(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDeal_device_code(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDeal_seq_group_no(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDeal_seq_no(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDeal_station(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDeal_type(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setMain_type(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSub_type(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setArea_code(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setSam_code(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setLogical_code(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setRead_count(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setDeal_amount(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setBalance(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setDeal_time(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setLast_deal_dev_code(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setLast_deal_sq_no(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setLast_deal_amount(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setLast_deal_time(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setTac(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setDegrade_mode(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setIn_gate_station(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setIn_gate_dev(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setIn_gate_time(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setPay_type(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setPay_card_no(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setDestination_station(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setDeal_cause(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setDeal_total_amount(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setDeposit(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setDeal_fee(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setExpiry_date(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setLast_expiry_date(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setOper_id(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setWork_sq_no(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setInfo_id(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setIs_report(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setPhoneType(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setPara_1(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setPara_2(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setPara_3(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Station entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Station entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Station entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
